// <auto-generated />
namespace Vjestina2015_Projekt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OglasOznake : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OglasOznake));
        
        string IMigrationMetadata.Id
        {
            get { return "201601070827280_OglasOznake"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
